### ISSUE TITLE
Add bug solution/fix to bug discussion page

### ISSUE THREAD

**Issue by thundergolfer** [bamos/densenet.pytorch#1]
Hey, 

I think it would be good to include how your CIFAR-10 convergence problem was solved. At the moment the discussion page just includes problem details. 

Good to hear you got it working.

**Comment by bamos** [comment]
Hi @thundergolfer - I've added some more details everywhere, let me know if you're interested in anything else.

-Brandon.

**Comment by TontonTremblay** [comment]
``` If you are interested in using the DenseNet code in this repository, make sure your PyTorch version contains this patch and was downloaded after 2017-02-10.```
There is no link in the text.

**Comment by bamos** [comment]
@TontonTremblay - did you expect a link for `this patch`? I meant to refer to the PR that I linked in the sentence before, but for clarity I just added a link around `this patch` too.
