### ISSUE TITLE
Have it been tested on pytorch v0.2 and CIFAR100?

### ISSUE THREAD

**Issue by wandering007** [bamos/densenet.pytorch#11]

**Comment by Albert0147** [comment]
@wandering007  Have you reproduced the result of DenseNet 40 on CIFAR100? I have just got acc of 70.86%, lower than the 75.58% in paper.

**Comment by wandering007** [comment]
@Albert0147  Sorry, I forget it...

**Comment by Albert0147** [comment]
Sadly...
