### ISSUE TITLE
Is the DenseBlock Implementation correct?

### ISSUE THREAD

**Issue by anjishnu** [bamos/densenet.pytorch#12]
Looking at your DenseBlock implementation, I don't see how the activations of the earlier layers before the previous one are being propagated to the later layers. Is the implementation really the same as in the DenseNet paper?

**Comment by bamos** [comment]
Yes, the layers concatenate their input with output to passthrough connections.

**Comment by aimicm** [comment]
@anjishnu  I have the same question as-like you mentioned ，I also did not find the Dense connection in this code. ???
