### ISSUE TITLE
Is the `_make_dense` function make the dense block really?

### ISSUE THREAD

**Issue by acgtyrant** [bamos/densenet.pytorch#6]
See https://github.com/bamos/densenet.pytorch/blob/master/densenet.py#L107 

I think it just make a line, not a complete graph...

**Comment by bamos** [comment]
Look at the model graph here: https://github.com/bamos/densenet.pytorch/blob/master/images/model.png

It's not just a line because of the `torch.cats` in the `Bottleneck` and `SingleLayer` functions.

-Brandon.

**Comment by acgtyrant** [comment]
So it is!
