### ISSUE TITLE
How do you convert the target from numpy arrays to Tensor?

### ISSUE THREAD

**Issue by acgtyrant** [bamos/densenet.pytorch#7]
I find that [torchvision get target as numpy arrays](https://github.com/pytorch/vision/blob/master/torchvision/datasets/cifar.py#L49-L86).

But you [call its `cuda()` suddenly](https://github.com/bamos/densenet.pytorch/blob/master/train.py#L110-L113)! I think it is the Tensor already.

I read the source code again and again, I do not find any place that you have converted the target from numpy arrays to Tensor. Any idea? Thank you!

**Comment by bamos** [comment]
Hi, I set this conversion in the train and test loaders here:
https://github.com/bamos/densenet.pytorch/blob/master/train.py#L56

**Comment by acgtyrant** [comment]
But I think this `transform` only work for img, not for target. See https://github.com/pytorch/vision/blob/master/torchvision/datasets/cifar.py#L35-L39

**Comment by bamos** [comment]
Ah, you're right. I'm not sure what's going on with the targets, but they were definitely tensors when I last ran this project a few months ago. Are things not working anymore?

**Comment by acgtyrant** [comment]
I will try to do it in these days.

**Comment by acgtyrant** [comment]
I find the cause now: `torch.utils.data.DataLoader` called `default_collate` to puts each data field into a tensor with outer dimension batch size.

https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L82-L83

**Comment by bamos** [comment]
Good to know! Thanks for posting back here
